import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";

export const Cormorant = Cormorant_Garamond({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Gym Helper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Cormorant.className}>
      <body
        className={`antialiased`}
      >
        <>
          {children}
        </>
      </body>
    </html>
  );
}
